# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    echo_mine.mineService:
        class: AppBundle\Service\MineService
        arguments: [ '@doctrine.orm.entity_manager' ]
